# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QMOpenApiDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'WSZSDKTest', '~> 0.0.6' #openapisdk 测试库


pod 'Masonry'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'MJRefresh'
end
